### PR TITLE
Add autodetection for nVidia dGPU

### PR DESCRIPTION
**Pull request by KhazAkar**
Autodetection if nVidia dGPU is 3D accelerator or VGA controller

### CODE REVIEW

**Comment by sndirsch** [comment]
I don't think this will fly since there can be also other NVIDIA devices like a network card/chip. I've worked on a different patch, since indeed this appears to be broken currently.

**Comment by sndirsch** [comment]
Just submitted my patch. Could you give it a try? https://github.com/openSUSE/SUSEPrime/commit/7f89087298b00399774c26496e23d6bef024e0a3

**Comment by KhazAkar** [comment]
Your patch works too and don't have a drawback, when someone have other nVidia branded components like NIC, so I think your is better.

**Comment by sndirsch** [comment]
> Your patch works too and don't have a drawback, when someone have other nVidia branded components like NIC, so I think your is better.

Thanks for confirmation! :-)

**Pull request closed without merging**
